#!/usr/bin/env bash
# Configure Nginx to listen to port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on all port 80 for all active IPv4 IPs
ln -s /etc/sites-available/default etc/nginx/sites-enabled/default
# restart Nginx
service Nginx restart
